// Swedish translations for the admin field/section/collection labels that stomme-gen
// emits into config.yml. Keys are the exact English source strings; stomme-gen looks
// each up when cmsLocale resolves here and leaves anything unmapped in English (so a
// site's own custom labels, icon identifiers and dynamic page options stay as written).
// Add a labels.<locale>.js alongside this to support another language.
export default {
  // ── section / block type names ──
  'Hero': 'Hero',
  'Page header': 'Sidhuvud',
  'Rich text': 'Formaterad text',
  'Text + image': 'Text + bild',
  'Text + quote': 'Text + citat',
  'Quote / statement': 'Citat / uttalande',
  'Quote / highlighted statement': 'Citat / framhävt uttalande',
  'Statement panel (dark, big number)': 'Uttalandepanel (mörk, stort tal)',
  'Feature cards': 'Funktionskort',
  'Process / steps': 'Process / steg',
  'Principles / values': 'Principer / värderingar',
  'Pricing / plans': 'Priser / paket',
  'Plans': 'Paket',
  'Plan name': 'Paketnamn',
  'Period': 'Period',
  'Description': 'Beskrivning',
  'Features': 'Ingår (punkter)',
  'Feature': 'Punkt',
  'Highlight this plan': 'Framhäv detta paket',
  'e.g. "595 kr", "19 900 kr", "0 kr".': 'T.ex. "595 kr", "19 900 kr", "0 kr".',
  'Price prefix': 'Prisprefix',
  'Small word above the price, e.g. "från".': 'Litet ord ovanför priset, t.ex. "från".',
  'e.g. "/mån" or "engångspris". Blank for none.': 'T.ex. "/mån" eller "engångspris". Tomt = ingen.',
  'Small label, e.g. "populär".': 'Liten etikett, t.ex. "populär".',
  'Stat columns': 'Sifferkolumner',
  'Two or three side-by-side figures (e.g. a comparison). Replaces the single big number when filled.': 'Två–tre siffror sida vid sida (t.ex. en jämförelse). Ersätter det stora talet när ifyllt.',
  'Shown as a quiet text link beside the button.': 'Visas som en diskret textlänk bredvid knappen.',
  'Steps': 'Steg',
  'Tag after the number': 'Text efter numret',
  'Short word shown with the number, e.g. "talk".': 'Kort ord som visas vid numret, t.ex. "prata".',
  'Wrap words in *asterisks* to underline them.': 'Omge ord med *asterisker* för att stryka under dem.',
  'Narrow centers the hero in a reading column (best without side media).': 'Smal centrerar heron i en läskolumn (bäst utan media vid sidan).',
  'Second link group · heading': 'Andra länkgruppen · rubrik',
  'Second link group': 'Andra länkgruppen',
  'Optional extra column, e.g. your services.': 'Valfri extra kolumn, t.ex. dina tjänster.',
  'Extra narrow': 'Extra smal',
  'Intro (below the title)': 'Intro (under rubriken)',
  'Questions shown': 'Frågor som visas',
  'Pick specific questions (in order). Leave empty to use the tag filter or show all.': 'Välj specifika frågor (i ordning). Tomt = taggfiltret eller alla.',
  'Tag filter': 'Taggfilter',
  'Show every question carrying this tag (tags are set on the questions). Ignored when questions are picked above.': 'Visa alla frågor med denna tagg (taggar sätts på frågorna). Ignoreras när frågor valts ovan.',
  'Tags': 'Taggar',
  'Tag': 'Tagg',
  'Scope the question to pages: an FAQ block filtered on a tag (e.g. a service or town) shows every question carrying it.': 'Koppla frågan till sidor: ett FAQ-block med ett taggfilter (t.ex. en tjänst eller ort) visar alla frågor med taggen.',
  'The lede under the title — also the card text in service lists.': 'Ingressen under rubriken — även korttexten i tjänstelistor.',
  'Alignment': 'Justering',
  'Left': 'Vänster',
  'Centered': 'Centrerad',
  'Right': 'Höger',
  'How wide the quote column is. Narrow reads best.': 'Hur bred citatkolumnen är. Smal läses bäst.',
  'Where the quote column sits in the section (the text stays left-aligned).': 'Var citatkolumnen sitter i sektionen (texten förblir vänsterställd).',
  // ── tracking & cookies pane ──
  'Tracking & cookies': 'Spårning & cookies',
  'Enable tracking': 'Aktivera spårning',
  'Google Tag Manager ID': 'Google Tag Manager-ID',
  'Google Analytics 4 ID': 'Google Analytics 4-ID',
  'Meta (Facebook) Pixel ID': 'Meta (Facebook) Pixel-ID',
  'Privacy policy URL': 'URL till integritetspolicy',
  'Facts / stats': 'Fakta / statistik',
  'Stats / facts': 'Statistik / fakta',
  'Before / after': 'Före / efter',
  'Gallery': 'Galleri',
  'Specialist grid': 'Specialistrutnät',
  'Call to action (band)': 'Uppmaning (band)',
  'Call to action (box)': 'Uppmaning (ruta)',
  'Contact form (auto)': 'Kontaktformulär (auto)',
  'Logo / partner strip (auto)': 'Logotyp / partnerrad (auto)',
  'Checklist (ticked items)': 'Checklista (bockade punkter)',
  'Testimonials': 'Omdömen',
  // shortened block-type labels (kept concise so the Decap add-menu doesn't truncate)
  'Service cards': 'Tjänstekort',
  'Link chips': 'Länkchips',
  'Blog posts': 'Blogginlägg',
  'Posts (blog / news)': 'Inlägg (blogg / nyheter)',
  'Catalog (for sale)': 'Katalog (till salu)',
  'Highlighted quote': 'Framhävt citat',
  'Statement panel': 'Uttalandepanel',
  'Logo strip': 'Logotyprad',
  'Contact form': 'Kontaktformulär',

  // ── common field labels ──
  'Heading': 'Rubrik',
  'Heading (H1)': 'Rubrik (H1)',
  'Heading (optional)': 'Rubrik (valfritt)',
  'Sub-line (optional)': 'Underrad (valfritt)',
  'Eyebrow': 'Dårrad',
  'Intro': 'Ingress',
  'Body': 'Brödtext',
  'Body text': 'Brödtext',
  'Text': 'Text',
  'Title': 'Titel',
  'Tagline': 'Slogan',
  'Note': 'Notis',
  'Caption': 'Bildtext',
  'Label': 'Etikett',
  'Link label': 'Länktext',
  'Value': 'Värde',
  'Order': 'Ordning',
  'Style': 'Stil',
  'Layout': 'Layout',
  'Width': 'Bredd',
  'Columns': 'Kolumner',
  'Lines': 'Rader',
  'Items': 'Punkter',
  'Badge': 'Märke',
  'Badges': 'Märken',
  'Chip': 'Chip',
  'Cards': 'Kort',
  'List': 'Lista',
  'Quote': 'Citat',
  'Answer': 'Svar',
  'Question': 'Fråga',
  'Source / name': 'Källa / namn',
  'Description': 'Beskrivning',
  'Number label': 'Etikett för tal',
  'Big number': 'Stort tal',
  'Highlight': 'Markering',
  'Icon': 'Ikon',

  // ── links / buttons ──
  'Button': 'Knapp',
  'Button label': 'Knapptext',
  'Button label (optional)': 'Knapptext (valfritt)',
  'Button link': 'Knapplänk',
  'Link': 'Länk',
  'Link (optional)': 'Länk (valfritt)',
  'Custom URL': 'Egen URL',
  '…or a custom URL': '…eller en egen URL',
  'Page': 'Sida',
  'Pages': 'Sidor',

  // ── images / media ──
  'Image': 'Bild',
  'Images': 'Bilder',
  'Alt text': 'Alt-text',
  'Image alt text': 'Alt-text för bild',
  'Image (if “Image” chosen)': 'Bild (om ”Bild” valts)',
  'Before image': 'Bild (före)',
  'After image': 'Bild (efter)',
  'Image on left': 'Bild till vänster',
  'Quote on left': 'Citat till vänster',
  'Right-side media': 'Media till höger',
  'Logo': 'Logotyp',
  'Logo image (overrides text)': 'Logotypbild (ersätter text)',
  'Logo text (if no image)': 'Logotyptext (om ingen bild)',
  'Logo alt text': 'Alt-text för logotyp',
  'Logo accent': 'Logotypaccent',

  // ── contact ──
  'Email': 'E-post',
  'Phone': 'Telefon',
  'Phone (tel: link)': 'Telefon (tel:-länk)',

  // ── layout / style options ──
  'Auto': 'Auto',
  'Full width': 'Full bredd',
  'Narrow (reading column)': 'Smal (läskolumn)',
  'Split (index + reader)': 'Delad (index + läsare)',
  'Accordion': 'Dragspel',
  'None (text only)': 'Ingen (endast text)',
  'Numbered (01/02/03 instead of icons)': 'Numrerad (01/02/03 istället för ikoner)',
  'Standard (white)': 'Standard (vit)',
  'Light': 'Ljus',
  'Band': 'Band',
  'Accent band': 'Accentband',
  'Accent surface': 'Accentyta',
  'Dark': 'Mörk',
  'Tinted': 'Tonad',
  'Brand': 'Varumärke',
  'Secondary': 'Sekundär',
  "This block's accent colour (rule, icon or number) — not the eyebrow.": 'Blockets accentfärg (linje, ikon eller siffra) — inte dårraden.',
  'Text on brand': 'Text på varumärke',
  'Background': 'Bakgrund',

  // ── cover block (full-bleed photo / video) ──
  'Cover (full-bleed)': 'Helbild (full bredd)',
  'Full-bleed banner — a background photo or muted looping video, with overlaid heading, text and buttons.': 'Helbildsbanner — ett bakgrundsfoto eller en tyst loopad video, med rubrik, text och knappar ovanpå.',
  'Second button label': 'Andra knappens text',
  'Second button link': 'Andra knappens länk',
  'Video (looping)': 'Video (loopad)',
  'Gradient (no image)': 'Gradient (ingen bild)',
  'Animated (no image)': 'Animerad (ingen bild)',
  'A photo, a looping video, a generated gradient, or an animated block pattern — both gradient and animated follow your brand colour, no asset needed.': 'Ett foto, en loopad video, en genererad gradient, eller ett animerat blockmönster — både gradient och animerad följer din varumärkesfärg, ingen fil behövs.',
  'Press Enter for a line break.': 'Tryck Enter för en radbrytning.',
  'A still photo, a muted looping video, or a generated gradient (no asset — follows your brand colour).': 'Ett stillbildsfoto, en tyst loopad video, eller en genererad gradient (ingen fil — följer din varumärkesfärg).',
  'A still photo, or a muted looping video.': 'Ett stillbildsfoto, eller en tyst loopad video.',
  'Background image / video poster': 'Bakgrundsbild / videoposter',
  'Video file (if “Video”)': 'Videofil (om ”Video”)',
  'Uploaded MP4/WebM — muted + looping. The image shows until it plays, and on reduced-motion.': 'Uppladdad MP4/WebM — tyst + loopad. Bilden visas tills den spelas, och vid reducerad rörelse.',
  '…or video URL': '…eller video-URL',
  'External MP4/WebM URL. Used instead of an uploaded file if filled.': 'Extern MP4/WebM-URL. Används istället för uppladdad fil om ifylld.',
  'Darken (overlay)': 'Mörkning (overlay)',
  'Medium': 'Mellan',
  'Strong': 'Stark',
  'How much to darken the media so the text stays readable.': 'Hur mycket mediet mörkas så att texten förblir läsbar.',
  'Text position': 'Textposition',
  'Bottom left': 'Nere till vänster',
  'Centered': 'Centrerad',
  'Height': 'Höjd',
  'Tall': 'Hög',
  'Gradient': 'Gradient',
  'Tall fills the viewport (good with a Gradient or Dark background).': 'Hög fyller hela skärmen (bra med Gradient- eller Mörk bakgrund).',
  'Top': 'Överst',
  'Center': 'Centrerat',
  'Bottom': 'Nederst',
  'Where the text sits in a Tall hero.': 'Var texten sitter i en hög hero.',
  'Sticky header': 'Fäst sidhuvud',
  'Header stays fixed at the top while scrolling. Default: it scrolls away with the page.': 'Sidhuvudet stannar kvar högst upp vid scrollning. Standard: det rullar bort med sidan.',

  // ── nav links + dropdowns ──
  '— No page —': '— Ingen sida —',
  'Dropdown from collection': 'Rullgardin från samling',
  '…or manual sub-links': '…eller egna underlänkar',
  'External link, tel: or mailto: — overrides the page above.': 'Extern länk, tel: eller mailto: — åsidosätter sidan ovan.',
  'Optional. Fill a dropdown with every entry of a collection (e.g. all services). Overrides manual sub-links below.': 'Valfritt. Fyll en rullgardin med alla poster i en samling (t.ex. alla tjänster). Åsidosätter egna underlänkar nedan.',
  'Blog': 'Blogg',

  // ── hero "highlights" + "motif" media ──
  'Highlights (icon + title + line)': 'Höjdpunkter (ikon + titel + rad)',
  'Motif (animated, no image)': 'Mönster (animerat, ingen bild)',
  'Highlights (if “Highlights” chosen)': 'Höjdpunkter (om ”Höjdpunkter” valts)',
  'A few key points shown as a stacked panel beside the heading.': 'Några nyckelpunkter som visas som en panel bredvid rubriken.',
  // ── textImage aside ──
  'Aside · heading': 'Sidoruta · rubrik',
  'Aside · text': 'Sidoruta · text',
  'Aside · button label': 'Sidoruta · knapptext',
  'Aside · button link': 'Sidoruta · knapplänk',

  // ── settings / chrome collections ──
  'Settings': 'Inställningar',
  'Site & contact': 'Webbplats & kontakt',
  'Site name': 'Webbplatsnamn',
  'Business name': 'Företagsnamn',
  'Favicon': 'Favikon',
  'Home-screen icon': 'Hemskärmsikon',
  'Social share image': 'Delningsbild',
  'Company name — used in the footer ©, the contact card, and search structured data. Not a page title.': 'Företagsnamn — används i sidfotens ©, kontaktkortet och sökstrukturdata. Inte en sidtitel.',
  'Navigation': 'Navigering',
  'Header': 'Sidhuvud',
  'Menu links': 'Menylänkar',
  'Footer': 'Sidfot',
  // footer pane fields + hints
  'Dark footer': 'Mörk sidfot',
  'Use the dark surface for the footer.': 'Använd den mörka ytan för sidfoten.',
  'A line under the logo.': 'En rad under logotypen.',
  'Show quick links': 'Visa snabblänkar',
  'Quick links · heading': 'Snabblänkar · rubrik',
  'Quick links': 'Snabblänkar',
  'A path like /about, or a full URL.': 'En sökväg som /om-oss, eller en fullständig URL.',
  'Show service areas': 'Visa tjänsteområden',
  'Adds a column linking every entry in the Areas collection.': 'Lägger till en kolumn som länkar varje post i Områden-samlingen.',
  'Service areas · heading': 'Tjänsteområden · rubrik',
  'Legal links (bottom bar)': 'Juridiska länkar (nedre raden)',
  'A path like /privacy, or a full URL.': 'En sökväg som /integritet, eller en fullständig URL.',
  'Appended to the © line.': 'Läggs till på ©-raden.',
  // logo (Identity) + header/footer show toggles
  'Shown in the header and footer (each chooses what to display).': 'Visas i sidhuvud och sidfot (var och en väljer vad som visas).',
  'Show logo mark': 'Visa logotypmärke',
  'Show wordmark text': 'Visa ordmärkestext',
  'Show the logo image (set under Identity) in the header.': 'Visa logotypbilden (anges under Identitet) i sidhuvudet.',
  'Show the wordmark text (set under Identity) in the header.': 'Visa ordmärkestexten (anges under Identitet) i sidhuvudet.',
  'Show the logo image (set under Identity) in the footer.': 'Visa logotypbilden (anges under Identitet) i sidfoten.',
  'Show the wordmark text (set under Identity) in the footer.': 'Visa ordmärkestexten (anges under Identitet) i sidfoten.',
  'Theme colours': 'Temafärger',
  // theme colour fields (role-based labels + hints)
  'Primary': 'Primärfärg',
  'Text on primary': 'Text på primärfärg',
  'Tinted surface': 'Tonad yta',
  'Page background': 'Sidbakgrund',
  'Borders & lines': 'Kantlinjer',
  'Accent': 'Accentfärg',
  'Buttons, links and key accents.': 'Knappar, länkar och viktiga accenter.',
  'Default body-text colour.': 'Brödtextens standardfärg.',
  'Button labels and text on dark/brand bands.': 'Knapptext och text på mörka band / primärfärg.',
  'Soft background for highlighted sections.': 'Mjuk bakgrund för framhävda sektioner.',
  'The main page background.': 'Sidans huvudbakgrund.',
  'Card borders, dividers, rules.': 'Kortkanter, avdelare och linjer.',
  'Secondary accent — badges, small highlights.': 'Sekundär accent — märken och små framhävningar.',
  // eyebrow style + colour (site-wide)
  'Eyebrow style': 'Dårradsstil',
  'Eyebrow colour': 'Dårradsfärg',
  'The small label above headings (e.g. “OUR SERVICES”) — site-wide.': 'Den lilla etiketten ovanför rubriker (t.ex. ”VÅRA TJÄNSTER”) — för hela webbplatsen.',
  'Which accent the eyebrow marker uses.': 'Vilken accent dårradens markör använder.',
  'Dash': 'Streck',
  'Bold (no marker)': 'Fet (ingen markör)',
  'Dark section background': 'Mörk sektion · bakgrund',
  'Dark section text': 'Mörk sektion · text',
  'Dark section borders': 'Mörk sektion · kantlinjer',
  'Background for blocks set to the Dark surface. Empty = derived from Primary.': 'Bakgrund för block med ytan Mörk. Tom = härleds från primärfärgen.',
  'Text colour on dark sections. Empty = a light off-white.': 'Textfärg på mörka sektioner. Tom = ljust benvit.',
  'Card borders / dividers on dark sections. Empty = a faint light rule.': 'Kortkanter / avdelare på mörka sektioner. Tom = svag ljus linje.',
  // fonts
  'Heading font': 'Rubriktypsnitt',
  'Body font': 'Brödtextstypsnitt',
  'Custom font file': 'Egen typsnittsfil',
  'Custom heading font file': 'Eget rubriktypsnitt (fil)',
  'Custom body font file': 'Eget brödtextstypsnitt (fil)',
  'Used when Heading font = Custom. A .woff2 / .woff / .ttf / .otf file (a font file, not an SVG).': 'Används när Rubriktypsnitt = Eget. En .woff2 / .woff / .ttf / .otf-fil (en typsnittsfil, inte en SVG).',
  'Used when Body font = Custom. Leave empty to reuse the heading font for body.': 'Används när Brödtextstypsnitt = Eget. Lämna tomt för att återanvända rubriktypsnittet.',
  // logo text size/weight
  'Logo text size': 'Logotyp · textstorlek',
  'Logo text weight': 'Logotyp · textvikt',
  'Small': 'Liten',
  'Large': 'Stor',
  'Extra large': 'Extra stor',
  'Bold': 'Fet',
  'Heavy': 'Tjock',
  'Text logo only (ignored with a logo image).': 'Endast textlogotyp (ignoreras med bild).',
  'Text logo only.': 'Endast textlogotyp.',
  'System (default)': 'System (standard)',
  'Serif (elegant headlines)': 'Serif (eleganta rubriker)',
  'Grotesk (clean sans)': 'Grotesk (ren sans)',
  'Geometric (Futura)': 'Geometrisk (Futura)',
  'Rounded': 'Rundad',
  'Custom (uploaded below)': 'Eget (uppladdat nedan)',
  'Font for headings. Empty = system default.': 'Typsnitt för rubriker. Tom = systemstandard.',
  'Font for body text. Empty = system default.': 'Typsnitt för brödtext. Tom = systemstandard.',
  'A .woff2 / .woff / .ttf / .otf file. Used where a font above is set to Custom. (A font file, not an SVG.)': 'En .woff2 / .woff / .ttf / .otf-fil. Används där ett typsnitt ovan är satt till Eget. (En typsnittsfil, inte en SVG.)',
  'Optional — just a reminder of which font this is.': 'Valfritt — bara en påminnelse om vilket typsnitt det är.',
  'Partners': 'Partner',
  'Partners lead-in': 'Partner-ingress',
  'Facts (optional — defaults to the site’s settings facts)': 'Fakta (valfritt — använder annars sidans inställningsfakta)',
  'FAQ': 'Vanliga frågor',
  'SEO': 'SEO',
  'SEO title': 'SEO-titel',
  'SEO description': 'SEO-beskrivning',
  'Sections · build the page (drag to reorder)': 'Sektioner · bygg sidan (dra för att ändra ordning)',

  // ── label_singular ──
  'Section': 'Sektion',

  // ── block gallery: group names + page chrome ──
  'Hero & headers': 'Hero & sidhuvuden',
  'Cards & lists': 'Kort & listor',
  'Quote & highlight': 'Citat & framhävning',
  'Numbers': 'Siffror',
  'From collections': 'Från samlingar',
  'Calls to action': 'Uppmaningar',
  'Automatic': 'Automatiska',
  'Block gallery': 'Blockgalleri',
  'Sections you can add': 'Sektioner du kan lägga till',
  'What each section produces. Keep this open beside /admin while you build a page.': 'Vad varje sektion ger. Ha den öppen bredvid /admin medan du bygger en sida.',
  'Filter sections…': 'Filtrera sektioner…',
  'No matches.': 'Inga träffar.',
  'Reads from a collection': 'Läser från en samling',

  // ── block gallery: one-line summaries (what each section produces) ──
  'Full-width intro — eyebrow, H1, text and a button, with an optional image, highlights list or animated motif beside it.': 'Intro i full bredd — dårrad, H1, text och knapp, med valfri bild, höjdpunktslista eller animerat mönster bredvid.',
  'Page title band (light or dark): eyebrow, H1, intro and an optional button.': 'Sidtitelband (ljust eller mörkt): dårrad, H1, ingress och en valfri knapp.',
  'A block of rich (markdown) text with an optional heading.': 'Ett block med formaterad text (markdown) och en valfri rubrik.',
  'Grid of feature cards — icon or number, title and text; cards can link.': 'Rutnät med funktionskort — ikon eller siffra, titel och text; korten kan länka.',
  'Service cards pulled from your Services collection.': 'Tjänstekort hämtade från din Tjänster-samling.',
  'Row of principle / value cards (icon, title, text).': 'Rad med kort för principer/värderingar (ikon, titel, text).',
  'Grid of specialist / team profile cards.': 'Rutnät med specialist-/teamprofiler.',
  'Numbered process — a sequence of steps.': 'Numrerad process — en följd av steg.',
  'Ticked checklist items in one or two columns.': 'Bockade checklistpunkter i en eller två kolumner.',
  'Image grid (2–3 columns) with optional captions.': 'Bildrutnät (2–3 kolumner) med valfria bildtexter.',
  'A before / after image pair.': 'Ett bildpar med före/efter.',
  'Text beside an image (image on the left or right).': 'Text bredvid en bild (bild till vänster eller höger).',
  'Body text paired with a pulled-out quote.': 'Brödtext tillsammans med ett utlyft citat.',
  'A single highlighted quote or statement.': 'Ett enskilt framhävt citat eller uttalande.',
  'Dark panel with a big number, statement and badges.': 'Mörk panel med ett stort tal, uttalande och märken.',
  'Customer testimonials from your Testimonials collection.': 'Kundomdömen från din Omdömen-samling.',
  'Chip links from your Areas collection (e.g. towns you serve).': 'Länkchips från din Områden-samling (t.ex. orter ni täcker).',
  'List of the latest blog posts.': 'Lista över de senaste blogginläggen.',
  'List of the latest posts — featured lead + a card grid with cover images. Works with the blog or any article listing.': 'Lista över de senaste inläggen — framhävt försteinlägg + ett kortrutnät med omslagsbilder. Fungerar med bloggen eller valfri artikellistning.',
  'Full-width call-to-action band with a button.': 'Uppmaningsband i full bredd med en knapp.',
  'A boxed call-to-action: heading, text and a button.': 'En inramad uppmaning: rubrik, text och en knapp.',
  'FAQ from your FAQ collection — list, accordion, cards or split layout.': 'Vanliga frågor från din FAQ-samling — lista, dragspel, kort eller delad layout.',
  'A row of stats / facts (label + value).': 'En rad med statistik/fakta (etikett + värde).',
  'Logo / partner strip, filled automatically from settings.': 'Logotyp-/partnerrad som fylls automatiskt från inställningarna.',
  'Contact form, rendered automatically.': 'Kontaktformulär som renderas automatiskt.',

  // ── collection editors (testimonials · services · areas/towns · posts) ──
  'Name': 'Namn',
  'Role / company': 'Roll / företag',
  'Testimonial': 'Omdöme',
  'Title (H1)': 'Titel (H1)',
  'Short label (menus/cards)': 'Kort etikett (menyer/kort)',
  'Summary': 'Sammanfattning',
  'Bullet': 'Punkt',
  'Bullets': 'Punkter',
  'Service': 'Tjänst',
  'Services': 'Tjänster',
  'Services shown': 'Tjänster som visas',
  'Services offered here': 'Tjänster som erbjuds här',
  'Pick which services appear (in order). Leave empty to show all.': 'Välj vilka tjänster som visas (i ordning). Lämna tomt för att visa alla.',
  'Service areas': 'Tjänsteområden',
  'Area': 'Område',
  'Town name': 'Ortsnamn',
  'Page heading (H1)': 'Sidrubrik (H1)',
  'Hero subtitle': 'Hero-underrubrik',
  'Hero note': 'Hero-notis',
  'Why us here (paragraphs)': 'Varför oss här (stycken)',
  'Problems we solve': 'Problem vi löser',
  'Problem': 'Problem',
  'Districts / areas': 'Distrikt / områden',
  'District': 'Distrikt',
  'Local case': 'Lokalt exempel',
  'Blog posts': 'Blogginlägg',
  'Post': 'Inlägg',
  'Date': 'Datum',
  'Excerpt': 'Utdrag',
  'Cover image': 'Omslagsbild',
  'Featured first post': 'Framhävt första inlägg',
  'Image previews': 'Bildförhandsvisningar',
  'Show the newest post as a large lead card.': 'Visa det senaste inlägget som ett stort ledande kort.',

  // ── catalog / listings ──
  'Catalog – items for sale (from a listing)': 'Katalog – varor till salu (från en listning)',
  'For-sale items from a catalog listing — filterable cards with cover, status badge, price and specs.': 'Varor till salu från en katalog-listning — filtrerbara kort med bild, statusmärke, pris och specifikationer.',
  'Price': 'Pris',
  'Status': 'Status',
  'Category': 'Kategori',
  'Category filters': 'Kategorifilter',
  'Specs': 'Specifikationer',
  'Date added': 'Tillagd',
  'Available': 'Tillgänglig',
  'Reserved': 'Reserverad',
  'Sold': 'Såld',

  // ── contact form + thank-you ──
  'Intro / description': 'Intro / beskrivning',
  'Field label — name': 'Fältetikett — namn',
  'Field label — email': 'Fältetikett — e-post',
  'Field label — phone': 'Fältetikett — telefon',
  'Show the phone field': 'Visa telefonfältet',
  'Field label — message': 'Fältetikett — meddelande',
  'Submit button text': 'Text på skicka-knappen',
  'Show the direct-contact card': 'Visa direktkontaktkortet',
  'Opening hours': 'Öppettider',
  // contact pane — address / hours / away / socials
  'Address': 'Adress',
  'Street': 'Gatuadress',
  'Postcode': 'Postnummer',
  'City': 'Ort',
  'Country': 'Land',
  'Latitude (map)': 'Latitud (karta)',
  'Longitude (map)': 'Longitud (karta)',
  'Days': 'Dagar',
  'Hours': 'Tider',
  'Holiday / special hours': 'Helg- / specialtider',
  'When': 'När',
  'Note': 'Notis',
  'Away banner': 'Frånvarobanner',
  'Show the away banner': 'Visa frånvarobannern',
  'Auto-hide after': 'Dölj automatiskt efter',
  'Social profiles': 'Sociala profiler',
  'Platform': 'Plattform',
  'Form confirmation': 'Formulärbekräftelse',
  'Message': 'Meddelande',
  'Primary button': 'Primärknapp',
  'Second button (optional)': 'Andra knappen (valfritt)',
  'Blank = localized default (\"Back to home\").': 'Tom = lokaliserad standard (”Till startsidan”).',
  'Leave blank for a single button.': 'Lämna tom för en enda knapp.',
  'Home (/)': 'Startsida (/)',
  'A contact form with an optional direct-contact card. Heading, intro, field labels and layout are all editable.': 'Ett kontaktformulär med ett valfritt direktkontaktkort. Rubrik, intro, fältetiketter och layout går att redigera.',

  // ── hints ──
  '1 or 2.': '1 eller 2.',
  '2 or 3.': '2 eller 3.',
  'E.g. "Read more". Shown only if the card has a link.': 'T.ex. ”Läs mer”. Visas bara om kortet har en länk.',
  'External link, tel: or mailto:. Used if filled.': 'Extern länk, tel: eller mailto:. Används om ifylld.',
  'Narrow keeps text legible; full uses the whole section width.': 'Smal håller texten läsbar; full använder hela sektionens bredd.',
  'Optional icon.': 'Valfri ikon.',
  'Pick a page on the site.': 'Välj en sida på webbplatsen.',
  'Small uppercase label above the heading.': 'Liten versal etikett ovanför rubriken.',
  'The surface behind the section — for rhythm between blocks.': 'Ytan bakom sektionen — för rytm mellan block.',
  'What shows beside the heading. Default: none.': 'Vad som visas bredvid rubriken. Standard: ingen.',
};
