// Swedish translations for the admin field/section/collection labels that stomme-gen
// emits into config.yml. Keys are the exact English source strings; stomme-gen looks
// each up when cmsLocale resolves here and leaves anything unmapped in English (so a
// site's own custom labels, icon identifiers and dynamic page options stay as written).
// Add a labels.<locale>.js alongside this to support another language.
export default {
  // ── section / block type names ──
  'Hero': 'Hero',
  'Page header': 'Sidhuvud',
  'Rich text': 'Formaterad text',
  'Text + image': 'Text + bild',
  'Text + quote': 'Text + citat',
  'Quote / statement': 'Citat / uttalande',
  'Quote / highlighted statement': 'Citat / framhävt uttalande',
  'Statement panel (dark, big number)': 'Uttalandepanel (mörk, stort tal)',
  'Operations / telemetry panel': 'Drift / telemetripanel',
  'Feature cards': 'Funktionskort',
  'Process / steps': 'Process / steg',
  'Principles / values': 'Principer / värderingar',
  'Facts / stats': 'Fakta / statistik',
  'Stats / facts': 'Statistik / fakta',
  'Before / after': 'Före / efter',
  'Gallery': 'Galleri',
  'Specialist grid': 'Specialistrutnät',
  'Call to action (band)': 'Uppmaning (band)',
  'Call to action (box)': 'Uppmaning (ruta)',
  'Contact form (auto)': 'Kontaktformulär (auto)',
  'Logo / partner strip (auto)': 'Logotyp / partnerrad (auto)',
  'Checklist (ticked items)': 'Checklista (bockade punkter)',

  // ── common field labels ──
  'Heading': 'Rubrik',
  'Heading (H1)': 'Rubrik (H1)',
  'Heading (optional)': 'Rubrik (valfritt)',
  'Sub-line (optional)': 'Underrad (valfritt)',
  'Eyebrow': 'Dårrad',
  'Intro': 'Ingress',
  'Body': 'Brödtext',
  'Body text': 'Brödtext',
  'Text': 'Text',
  'Title': 'Titel',
  'Tagline': 'Slogan',
  'Note': 'Notis',
  'Caption': 'Bildtext',
  'Label': 'Etikett',
  'Link label': 'Länktext',
  'Value': 'Värde',
  'Order': 'Ordning',
  'Style': 'Stil',
  'Layout': 'Layout',
  'Width': 'Bredd',
  'Columns': 'Kolumner',
  'Lines': 'Rader',
  'Items': 'Punkter',
  'Badge': 'Märke',
  'Badges': 'Märken',
  'Chip': 'Chip',
  'Cards': 'Kort',
  'List': 'Lista',
  'Quote': 'Citat',
  'Answer': 'Svar',
  'Question': 'Fråga',
  'Source / name': 'Källa / namn',
  'Description': 'Beskrivning',
  'Number label': 'Etikett för tal',
  'Big number': 'Stort tal',
  'Highlight': 'Markering',
  'Icon': 'Ikon',

  // ── links / buttons ──
  'Button': 'Knapp',
  'Button label': 'Knapptext',
  'Button label (optional)': 'Knapptext (valfritt)',
  'Button link': 'Knapplänk',
  'Link': 'Länk',
  'Link (optional)': 'Länk (valfritt)',
  'Custom URL': 'Egen URL',
  '…or a custom URL': '…eller en egen URL',
  'Page': 'Sida',
  'Pages': 'Sidor',

  // ── images / media ──
  'Image': 'Bild',
  'Images': 'Bilder',
  'Alt text': 'Alt-text',
  'Image alt text': 'Alt-text för bild',
  'Image (if “Image” chosen)': 'Bild (om ”Bild” valts)',
  'Before image': 'Bild (före)',
  'After image': 'Bild (efter)',
  'Image on left': 'Bild till vänster',
  'Quote on left': 'Citat till vänster',
  'Right-side media': 'Media till höger',
  'Logo': 'Logotyp',
  'Logo image (overrides text)': 'Logotypbild (ersätter text)',
  'Logo text (if no image)': 'Logotyptext (om ingen bild)',
  'Logo alt text': 'Alt-text för logotyp',
  'Logo accent': 'Logotypaccent',

  // ── contact ──
  'Email': 'E-post',
  'Phone': 'Telefon',
  'Phone (tel: link)': 'Telefon (tel:-länk)',

  // ── layout / style options ──
  'Auto': 'Auto',
  'Full width': 'Full bredd',
  'Narrow (reading column)': 'Smal (läskolumn)',
  'Split (index + reader)': 'Delad (index + läsare)',
  'Accordion': 'Dragspel',
  'None (text only)': 'Ingen (endast text)',
  'Numbered (01/02/03 instead of icons)': 'Numrerad (01/02/03 istället för ikoner)',
  'Standard (white)': 'Standard (vit)',
  'Light': 'Ljus',
  'Dark (band)': 'Mörk (band)',
  'Accent band': 'Accentband',
  'Accent surface': 'Accentyta',
  'Tinted': 'Tonad',
  'Brand': 'Varumärke',
  'Text on brand': 'Text på varumärke',
  'Background': 'Bakgrund',

  // ── hero "energy flow" variant ──
  'Energy flow': 'Energiflöde',
  'Flow · chip label (if “Energy flow”)': 'Flöde · chip-etikett (om ”Energiflöde”)',
  'Flow · steps (if “Energy flow”)': 'Flöde · steg (om ”Energiflöde”)',
  // ── statPanel "operations" variant ──
  'Ops · corner stamp (if “Operations”)': 'Drift · hörnstämpel (om ”Drift”)',
  'Ops · telemetry chips (if “Operations”)': 'Drift · telemetri-chips (om ”Drift”)',
  // ── textImage aside ──
  'Aside · heading': 'Sidoruta · rubrik',
  'Aside · text': 'Sidoruta · text',
  'Aside · button label': 'Sidoruta · knapptext',
  'Aside · button link': 'Sidoruta · knapplänk',

  // ── settings / chrome collections ──
  'Settings': 'Inställningar',
  'Site & contact': 'Webbplats & kontakt',
  'Site name': 'Webbplatsnamn',
  'Navigation': 'Navigering',
  'Menu links': 'Menylänkar',
  'Footer': 'Sidfot',
  'Theme colours': 'Temafärger',
  'Partners': 'Partner',
  'Partners lead-in': 'Partner-ingress',
  'Facts (optional — defaults to the site’s settings facts)': 'Fakta (valfritt — använder annars sidans inställningsfakta)',
  'FAQ': 'Vanliga frågor',
  'SEO': 'SEO',
  'SEO title': 'SEO-titel',
  'SEO description': 'SEO-beskrivning',
  'Sections · build the page (drag to reorder)': 'Sektioner · bygg sidan (dra för att ändra ordning)',

  // ── label_singular ──
  'Section': 'Sektion',

  // ── block gallery: group names + page chrome ──
  'Hero & headers': 'Hero & sidhuvuden',
  'Cards & lists': 'Kort & listor',
  'Quote & highlight': 'Citat & framhävning',
  'Numbers': 'Siffror',
  'From collections': 'Från samlingar',
  'Calls to action': 'Uppmaningar',
  'Automatic': 'Automatiska',
  'Block gallery': 'Blockgalleri',
  'Sections you can add': 'Sektioner du kan lägga till',
  'What each section produces. Keep this open beside /admin while you build a page.': 'Vad varje sektion ger. Ha den öppen bredvid /admin medan du bygger en sida.',
  'Filter sections…': 'Filtrera sektioner…',
  'No matches.': 'Inga träffar.',
  'Reads from a collection': 'Läser från en samling',

  // ── hints ──
  '1 or 2.': '1 eller 2.',
  '2 or 3.': '2 eller 3.',
  'E.g. "Read more". Shown only if the card has a link.': 'T.ex. ”Läs mer”. Visas bara om kortet har en länk.',
  'External link, tel: or mailto:. Used if filled.': 'Extern länk, tel: eller mailto:. Används om ifylld.',
  'Narrow keeps text legible; full uses the whole section width.': 'Smal håller texten läsbar; full använder hela sektionens bredd.',
  'Optional icon.': 'Valfri ikon.',
  'Pick a page on the site.': 'Välj en sida på webbplatsen.',
  'Small uppercase label above the heading.': 'Liten versal etikett ovanför rubriken.',
  'The surface behind the section — for rhythm between blocks.': 'Ytan bakom sektionen — för rytm mellan block.',
  'What shows beside the heading. Default: none.': 'Vad som visas bredvid rubriken. Standard: ingen.',
};
