// Swedish translations for the admin field/section/collection labels that stomme-gen
// emits into config.yml. Keys are the exact English source strings; stomme-gen looks
// each up when cmsLocale resolves here and leaves anything unmapped in English (so a
// site's own custom labels, icon identifiers and dynamic page options stay as written).
// Add a labels.<locale>.js alongside this to support another language.
export default {
  // ── section / block type names ──
  'Hero': 'Hero',
  'Page header': 'Sidhuvud',
  'Rich text': 'Formaterad text',
  'Text + image': 'Text + bild',
  'Text + quote': 'Text + citat',
  'Quote / statement': 'Citat / uttalande',
  'Quote / highlighted statement': 'Citat / framhävt uttalande',
  'Statement panel (dark, big number)': 'Uttalandepanel (mörk, stort tal)',
  'Operations / telemetry panel': 'Drift / telemetripanel',
  'Feature cards': 'Funktionskort',
  'Process / steps': 'Process / steg',
  'Principles / values': 'Principer / värderingar',
  'Facts / stats': 'Fakta / statistik',
  'Stats / facts': 'Statistik / fakta',
  'Before / after': 'Före / efter',
  'Gallery': 'Galleri',
  'Specialist grid': 'Specialistrutnät',
  'Call to action (band)': 'Uppmaning (band)',
  'Call to action (box)': 'Uppmaning (ruta)',
  'Contact form (auto)': 'Kontaktformulär (auto)',
  'Logo / partner strip (auto)': 'Logotyp / partnerrad (auto)',
  'Checklist (ticked items)': 'Checklista (bockade punkter)',
  'Testimonials': 'Omdömen',
  // shortened block-type labels (kept concise so the Decap add-menu doesn't truncate)
  'Service cards': 'Tjänstekort',
  'Link chips': 'Länkchips',
  'Blog posts': 'Blogginlägg',
  'Catalog (for sale)': 'Katalog (till salu)',
  'Highlighted quote': 'Framhävt citat',
  'Statement panel': 'Uttalandepanel',
  'Logo strip': 'Logotyprad',
  'Contact form': 'Kontaktformulär',

  // ── common field labels ──
  'Heading': 'Rubrik',
  'Heading (H1)': 'Rubrik (H1)',
  'Heading (optional)': 'Rubrik (valfritt)',
  'Sub-line (optional)': 'Underrad (valfritt)',
  'Eyebrow': 'Dårrad',
  'Intro': 'Ingress',
  'Body': 'Brödtext',
  'Body text': 'Brödtext',
  'Text': 'Text',
  'Title': 'Titel',
  'Tagline': 'Slogan',
  'Note': 'Notis',
  'Caption': 'Bildtext',
  'Label': 'Etikett',
  'Link label': 'Länktext',
  'Value': 'Värde',
  'Order': 'Ordning',
  'Style': 'Stil',
  'Layout': 'Layout',
  'Width': 'Bredd',
  'Columns': 'Kolumner',
  'Lines': 'Rader',
  'Items': 'Punkter',
  'Badge': 'Märke',
  'Badges': 'Märken',
  'Chip': 'Chip',
  'Cards': 'Kort',
  'List': 'Lista',
  'Quote': 'Citat',
  'Answer': 'Svar',
  'Question': 'Fråga',
  'Source / name': 'Källa / namn',
  'Description': 'Beskrivning',
  'Number label': 'Etikett för tal',
  'Big number': 'Stort tal',
  'Highlight': 'Markering',
  'Icon': 'Ikon',

  // ── links / buttons ──
  'Button': 'Knapp',
  'Button label': 'Knapptext',
  'Button label (optional)': 'Knapptext (valfritt)',
  'Button link': 'Knapplänk',
  'Link': 'Länk',
  'Link (optional)': 'Länk (valfritt)',
  'Custom URL': 'Egen URL',
  '…or a custom URL': '…eller en egen URL',
  'Page': 'Sida',
  'Pages': 'Sidor',

  // ── images / media ──
  'Image': 'Bild',
  'Images': 'Bilder',
  'Alt text': 'Alt-text',
  'Image alt text': 'Alt-text för bild',
  'Image (if “Image” chosen)': 'Bild (om ”Bild” valts)',
  'Before image': 'Bild (före)',
  'After image': 'Bild (efter)',
  'Image on left': 'Bild till vänster',
  'Quote on left': 'Citat till vänster',
  'Right-side media': 'Media till höger',
  'Logo': 'Logotyp',
  'Logo image (overrides text)': 'Logotypbild (ersätter text)',
  'Logo text (if no image)': 'Logotyptext (om ingen bild)',
  'Logo alt text': 'Alt-text för logotyp',
  'Logo accent': 'Logotypaccent',

  // ── contact ──
  'Email': 'E-post',
  'Phone': 'Telefon',
  'Phone (tel: link)': 'Telefon (tel:-länk)',

  // ── layout / style options ──
  'Auto': 'Auto',
  'Full width': 'Full bredd',
  'Narrow (reading column)': 'Smal (läskolumn)',
  'Split (index + reader)': 'Delad (index + läsare)',
  'Accordion': 'Dragspel',
  'None (text only)': 'Ingen (endast text)',
  'Numbered (01/02/03 instead of icons)': 'Numrerad (01/02/03 istället för ikoner)',
  'Standard (white)': 'Standard (vit)',
  'Light': 'Ljus',
  'Dark (band)': 'Mörk (band)',
  'Accent band': 'Accentband',
  'Accent surface': 'Accentyta',
  'Dark': 'Mörk',
  'Tinted': 'Tonad',
  'Brand': 'Varumärke',
  'Text on brand': 'Text på varumärke',
  'Background': 'Bakgrund',

  // ── hero "energy flow" variant ──
  'Energy flow': 'Energiflöde',
  'Flow · chip label (if “Energy flow”)': 'Flöde · chip-etikett (om ”Energiflöde”)',
  'Flow · steps (if “Energy flow”)': 'Flöde · steg (om ”Energiflöde”)',
  // ── statPanel "operations" variant ──
  'Ops · corner stamp (if “Operations”)': 'Drift · hörnstämpel (om ”Drift”)',
  'Ops · telemetry readouts (if “Operations”)': 'Drift · telemetrimätvärden (om ”Drift”)',
  'Readout': 'Mätvärde',
  // ── textImage aside ──
  'Aside · heading': 'Sidoruta · rubrik',
  'Aside · text': 'Sidoruta · text',
  'Aside · button label': 'Sidoruta · knapptext',
  'Aside · button link': 'Sidoruta · knapplänk',

  // ── settings / chrome collections ──
  'Settings': 'Inställningar',
  'Site & contact': 'Webbplats & kontakt',
  'Site name': 'Webbplatsnamn',
  'Navigation': 'Navigering',
  'Menu links': 'Menylänkar',
  'Footer': 'Sidfot',
  'Theme colours': 'Temafärger',
  // theme colour fields (role-based labels + hints)
  'Primary': 'Primärfärg',
  'Text on primary': 'Text på primärfärg',
  'Tinted surface': 'Tonad yta',
  'Page background': 'Sidbakgrund',
  'Borders & lines': 'Kantlinjer',
  'Accent': 'Accentfärg',
  'Buttons, links and key accents.': 'Knappar, länkar och viktiga accenter.',
  'Default body-text colour.': 'Brödtextens standardfärg.',
  'Button labels and text on dark/brand bands.': 'Knapptext och text på mörka band / primärfärg.',
  'Soft background for highlighted sections.': 'Mjuk bakgrund för framhävda sektioner.',
  'The main page background.': 'Sidans huvudbakgrund.',
  'Card borders, dividers, rules.': 'Kortkanter, avdelare och linjer.',
  'Secondary accent — badges, small highlights.': 'Sekundär accent — märken och små framhävningar.',
  'Dark section background': 'Mörk sektion · bakgrund',
  'Dark section text': 'Mörk sektion · text',
  'Dark section borders': 'Mörk sektion · kantlinjer',
  'Background for blocks set to the Dark surface. Empty = derived from Primary.': 'Bakgrund för block med ytan Mörk. Tom = härleds från primärfärgen.',
  'Text colour on dark sections. Empty = a light off-white.': 'Textfärg på mörka sektioner. Tom = ljust benvit.',
  'Card borders / dividers on dark sections. Empty = a faint light rule.': 'Kortkanter / avdelare på mörka sektioner. Tom = svag ljus linje.',
  'Partners': 'Partner',
  'Partners lead-in': 'Partner-ingress',
  'Facts (optional — defaults to the site’s settings facts)': 'Fakta (valfritt — använder annars sidans inställningsfakta)',
  'FAQ': 'Vanliga frågor',
  'SEO': 'SEO',
  'SEO title': 'SEO-titel',
  'SEO description': 'SEO-beskrivning',
  'Sections · build the page (drag to reorder)': 'Sektioner · bygg sidan (dra för att ändra ordning)',

  // ── label_singular ──
  'Section': 'Sektion',

  // ── block gallery: group names + page chrome ──
  'Hero & headers': 'Hero & sidhuvuden',
  'Cards & lists': 'Kort & listor',
  'Quote & highlight': 'Citat & framhävning',
  'Numbers': 'Siffror',
  'From collections': 'Från samlingar',
  'Calls to action': 'Uppmaningar',
  'Automatic': 'Automatiska',
  'Block gallery': 'Blockgalleri',
  'Sections you can add': 'Sektioner du kan lägga till',
  'What each section produces. Keep this open beside /admin while you build a page.': 'Vad varje sektion ger. Ha den öppen bredvid /admin medan du bygger en sida.',
  'Filter sections…': 'Filtrera sektioner…',
  'No matches.': 'Inga träffar.',
  'Reads from a collection': 'Läser från en samling',

  // ── block gallery: one-line summaries (what each section produces) ──
  'Full-width intro — eyebrow, H1, text and a button, with optional image, energy-flow or ops panel beside it.': 'Intro i full bredd — dårrad, H1, text och knapp, med valfri bild, energiflöde eller driftpanel bredvid.',
  'Page title band (light or dark): eyebrow, H1, intro and an optional button.': 'Sidtitelband (ljust eller mörkt): dårrad, H1, ingress och en valfri knapp.',
  'A block of rich (markdown) text with an optional heading.': 'Ett block med formaterad text (markdown) och en valfri rubrik.',
  'Grid of feature cards — icon or number, title and text; cards can link.': 'Rutnät med funktionskort — ikon eller siffra, titel och text; korten kan länka.',
  'Service cards pulled from your Services collection.': 'Tjänstekort hämtade från din Tjänster-samling.',
  'Row of principle / value cards (icon, title, text).': 'Rad med kort för principer/värderingar (ikon, titel, text).',
  'Grid of specialist / team profile cards.': 'Rutnät med specialist-/teamprofiler.',
  'Numbered process — a sequence of steps.': 'Numrerad process — en följd av steg.',
  'Ticked checklist items in one or two columns.': 'Bockade checklistpunkter i en eller två kolumner.',
  'Image grid (2–3 columns) with optional captions.': 'Bildrutnät (2–3 kolumner) med valfria bildtexter.',
  'A before / after image pair.': 'Ett bildpar med före/efter.',
  'Text beside an image (image on the left or right).': 'Text bredvid en bild (bild till vänster eller höger).',
  'Body text paired with a pulled-out quote.': 'Brödtext tillsammans med ett utlyft citat.',
  'A single highlighted quote or statement.': 'Ett enskilt framhävt citat eller uttalande.',
  'Dark panel with a big number, statement and badges.': 'Mörk panel med ett stort tal, uttalande och märken.',
  'Customer testimonials from your Testimonials collection.': 'Kundomdömen från din Omdömen-samling.',
  'Chip links from your Areas collection (e.g. towns you serve).': 'Länkchips från din Områden-samling (t.ex. orter ni täcker).',
  'List of the latest blog posts.': 'Lista över de senaste blogginläggen.',
  'Full-width call-to-action band with a button.': 'Uppmaningsband i full bredd med en knapp.',
  'A boxed call-to-action: heading, text and a button.': 'En inramad uppmaning: rubrik, text och en knapp.',
  'FAQ from your FAQ collection — list, accordion, cards or split layout.': 'Vanliga frågor från din FAQ-samling — lista, dragspel, kort eller delad layout.',
  'A row of stats / facts (label + value).': 'En rad med statistik/fakta (etikett + värde).',
  'Logo / partner strip, filled automatically from settings.': 'Logotyp-/partnerrad som fylls automatiskt från inställningarna.',
  'Contact form, rendered automatically.': 'Kontaktformulär som renderas automatiskt.',

  // ── collection editors (testimonials · services · areas/towns · posts) ──
  'Name': 'Namn',
  'Role / company': 'Roll / företag',
  'Testimonial': 'Omdöme',
  'Title (H1)': 'Titel (H1)',
  'Short label (menus/cards)': 'Kort etikett (menyer/kort)',
  'Summary': 'Sammanfattning',
  'Bullet': 'Punkt',
  'Bullets': 'Punkter',
  'Service': 'Tjänst',
  'Services': 'Tjänster',
  'Services shown': 'Tjänster som visas',
  'Services offered here': 'Tjänster som erbjuds här',
  'Pick which services appear (in order). Leave empty to show all.': 'Välj vilka tjänster som visas (i ordning). Lämna tomt för att visa alla.',
  'Service areas': 'Tjänsteområden',
  'Area': 'Område',
  'Town name': 'Ortsnamn',
  'Page heading (H1)': 'Sidrubrik (H1)',
  'Hero subtitle': 'Hero-underrubrik',
  'Hero note': 'Hero-notis',
  'Why us here (paragraphs)': 'Varför oss här (stycken)',
  'Problems we solve': 'Problem vi löser',
  'Problem': 'Problem',
  'Districts / areas': 'Distrikt / områden',
  'District': 'Distrikt',
  'Local case': 'Lokalt exempel',
  'Blog posts': 'Blogginlägg',
  'Post': 'Inlägg',
  'Date': 'Datum',
  'Excerpt': 'Utdrag',
  'Cover image': 'Omslagsbild',
  'Featured first post': 'Framhävt första inlägg',
  'Image previews': 'Bildförhandsvisningar',
  'Show the newest post as a large lead card.': 'Visa det senaste inlägget som ett stort ledande kort.',

  // ── catalog / listings ──
  'Catalog – items for sale (from a listing)': 'Katalog – varor till salu (från en listning)',
  'For-sale items from a catalog listing — filterable cards with cover, status badge, price and specs.': 'Varor till salu från en katalog-listning — filtrerbara kort med bild, statusmärke, pris och specifikationer.',
  'Price': 'Pris',
  'Status': 'Status',
  'Category': 'Kategori',
  'Category filters': 'Kategorifilter',
  'Specs': 'Specifikationer',
  'Date added': 'Tillagd',
  'Available': 'Tillgänglig',
  'Reserved': 'Reserverad',
  'Sold': 'Såld',

  // ── hints ──
  '1 or 2.': '1 eller 2.',
  '2 or 3.': '2 eller 3.',
  'E.g. "Read more". Shown only if the card has a link.': 'T.ex. ”Läs mer”. Visas bara om kortet har en länk.',
  'External link, tel: or mailto:. Used if filled.': 'Extern länk, tel: eller mailto:. Används om ifylld.',
  'Narrow keeps text legible; full uses the whole section width.': 'Smal håller texten läsbar; full använder hela sektionens bredd.',
  'Optional icon.': 'Valfri ikon.',
  'Pick a page on the site.': 'Välj en sida på webbplatsen.',
  'Small uppercase label above the heading.': 'Liten versal etikett ovanför rubriken.',
  'The surface behind the section — for rhythm between blocks.': 'Ytan bakom sektionen — för rytm mellan block.',
  'What shows beside the heading. Default: none.': 'Vad som visas bredvid rubriken. Standard: ingen.',
};
