// The default block catalog — field definitions for the library blocks. Use it
// directly or extend it: `export const BLOCKS = [...defaultBlocks, ...mine]`.
import { headingFields, headingFieldsWith, linkField, imageField, iconField, surfaceField, accentField, widthField, cardListField, linkedCardListField, type BlockDef } from './src/kit.ts';

export const defaultBlocks: BlockDef[] = [
  {
    type: 'hero',
    label: 'Hero',
    group: 'Hero & headers',
    summary: 'Full-width intro — eyebrow, H1, text and a button, with an optional image, highlights list or animated motif beside it.',
    shape: 'hero',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', widget: 'string', required: false },
      { name: 'heading', label: 'Heading (H1)', widget: 'string' },
      { name: 'intro', label: 'Intro', widget: 'text', required: false },
      { name: 'ctaLabel', label: 'Button label', widget: 'string', required: false },
      linkField('ctaHref', 'Button link'),
      { name: 'cta2Label', label: 'Second button label', widget: 'string', required: false, hint: 'Shown as a quiet text link beside the button.' },
      linkField('cta2Href', 'Second button link'),
      {
        name: 'media',
        label: 'Right-side media',
        widget: 'select',
        required: false,
        default: 'none',
        options: [
          { label: 'None (text only)', value: 'none' },
          { label: 'Image', value: 'image' },
          { label: 'Highlights (icon + title + line)', value: 'highlights' },
          { label: 'Motif (animated, no image)', value: 'motif' },
        ],
        hint: 'What shows beside the heading. Default: none.',
      },
      imageField('image', 'Image (if “Image” chosen)'),
      { name: 'imageAlt', label: 'Image alt text', widget: 'string', required: false },
      {
        name: 'highlights',
        label: 'Highlights (if “Highlights” chosen)',
        widget: 'list',
        required: false,
        hint: 'A few key points shown as a stacked panel beside the heading.',
        fields: [iconField(), { name: 'title', label: 'Title', widget: 'string' }, { name: 'body', label: 'Text', widget: 'string', required: false }],
      },
      {
        name: 'height', label: 'Height', widget: 'select', required: false, default: 'normal',
        hint: 'Tall fills the viewport (good with a Gradient or Dark background).',
        options: [{ label: 'Normal', value: 'normal' }, { label: 'Tall', value: 'tall' }],
      },
      {
        name: 'align', label: 'Text position', widget: 'select', required: false, default: 'center',
        hint: 'Where the text sits in a Tall hero.',
        options: [{ label: 'Top', value: 'top' }, { label: 'Center', value: 'center' }, { label: 'Bottom', value: 'bottom' }],
      },
      {
        name: 'width', label: 'Width', widget: 'select', required: false, default: 'full',
        hint: 'Narrow centers the hero in a reading column (best without side media).',
        options: [{ label: 'Full width', value: 'full' }, { label: 'Narrow (reading column)', value: 'narrow' }],
      },
      surfaceField,
    ],
  },
  {
    type: 'cover',
    label: 'Cover (full-bleed)',
    group: 'Hero & headers',
    summary: 'Full-bleed banner — a background photo or muted looping video, with overlaid heading, text and buttons.',
    shape: 'hero',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', widget: 'string', required: false },
      { name: 'heading', label: 'Heading (H1)', widget: 'text', hint: 'Press Enter for a line break.' },
      { name: 'intro', label: 'Intro', widget: 'text', required: false },
      { name: 'ctaLabel', label: 'Button label', widget: 'string', required: false },
      linkField('ctaHref', 'Button link'),
      { name: 'cta2Label', label: 'Second button label', widget: 'string', required: false },
      linkField('cta2Href', 'Second button link'),
      {
        name: 'media',
        label: 'Background',
        widget: 'select',
        required: false,
        default: 'image',
        hint: 'A photo, a looping video, a generated gradient, or an animated block pattern — both gradient and animated follow your brand colour, no asset needed.',
        options: [
          { label: 'Image', value: 'image' },
          { label: 'Video (looping)', value: 'video' },
          { label: 'Gradient (no image)', value: 'gradient' },
          { label: 'Animated (no image)', value: 'animated' },
        ],
      },
      imageField('image', 'Background image / video poster'),
      { name: 'imageAlt', label: 'Image alt text', widget: 'string', required: false },
      { name: 'video', label: 'Video file (if “Video”)', widget: 'file', required: false, hint: 'Uploaded MP4/WebM — muted + looping. The image shows until it plays, and on reduced-motion.' },
      { name: 'videoUrl', label: '…or video URL', widget: 'string', required: false, hint: 'External MP4/WebM URL. Used instead of an uploaded file if filled.' },
      {
        name: 'overlay',
        label: 'Darken (overlay)',
        widget: 'select',
        required: false,
        default: 'medium',
        hint: 'How much to darken the media so the text stays readable.',
        options: [
          { label: 'Light', value: 'light' },
          { label: 'Medium', value: 'medium' },
          { label: 'Strong', value: 'strong' },
        ],
      },
      {
        name: 'align',
        label: 'Text position',
        widget: 'select',
        required: false,
        default: 'start',
        options: [
          { label: 'Bottom left', value: 'start' },
          { label: 'Centered', value: 'center' },
        ],
      },
      {
        name: 'height',
        label: 'Height',
        widget: 'select',
        required: false,
        default: 'tall',
        options: [
          { label: 'Tall', value: 'tall' },
          { label: 'Medium', value: 'medium' },
        ],
      },
    ],
  },
  {
    type: 'pageHeader',
    label: 'Page header',
    group: 'Hero & headers',
    summary: 'Page title band (light or dark): eyebrow, H1, intro and an optional button.',
    shape: 'band',
    fields: [
      { name: 'variant', label: 'Style', widget: 'select', required: false, default: 'light', options: [{ label: 'Light', value: 'light' }, { label: 'Band', value: 'dark' }] },
      widthField,
      { name: 'eyebrow', label: 'Eyebrow', widget: 'string', required: false },
      { name: 'heading', label: 'Heading (H1)', widget: 'string' },
      { name: 'intro', label: 'Intro', widget: 'text', required: false },
      { name: 'ctaLabel', label: 'Button label (optional)', widget: 'string', required: false },
      linkField('ctaHref', 'Button link'),
      surfaceField,
    ],
  },
  {
    type: 'prose',
    label: 'Rich text',
    group: 'Text',
    summary: 'A block of rich (markdown) text with an optional heading.',
    shape: 'prose',
    fields: [{ name: 'eyebrow', label: 'Eyebrow', widget: 'string', required: false, hint: 'Small uppercase label above the heading.' }, { name: 'heading', label: 'Heading (optional)', widget: 'string', required: false }, { name: 'body', label: 'Body', widget: 'markdown', required: false }, widthField, surfaceField],
  },
  {
    type: 'featureGrid',
    label: 'Feature cards',
    group: 'Cards & lists',
    summary: 'Grid of feature cards — icon or number, title and text; cards can link.',
    shape: 'grid',
    fields: [
      ...headingFields,
      linkedCardListField,
      { name: 'numbered', label: 'Numbered (01/02/03 instead of icons)', widget: 'boolean', required: false, default: false },
      accentField,
      surfaceField,
    ],
  },
  {
    type: 'serviceGrid',
    label: 'Service cards',
    group: 'From collections',
    summary: 'Service cards pulled from your Services collection.',
    shape: 'grid',
    collection: 'services',
    fields: [
      ...headingFields,
      { name: 'services', label: 'Services shown', widget: 'select', options: '$services', multiple: true, required: false, hint: 'Pick which services appear (in order). Leave empty to show all.' },
      surfaceField,
    ],
  },
  { type: 'pillars', label: 'Principles / values', group: 'Cards & lists', summary: 'Row of principle / value cards (icon, title, text).', shape: 'grid', fields: [...headingFields, cardListField, surfaceField] },
  {
    type: 'plans',
    label: 'Pricing / plans',
    group: 'Cards & lists',
    summary: 'A row of pricing plan cards — name, price, period, features and a button.',
    shape: 'grid',
    fields: [
      ...headingFields,
      {
        name: 'plans',
        label: 'Plans',
        widget: 'list',
        required: false,
        fields: [
          { name: 'name', label: 'Plan name', widget: 'string' },
          { name: 'pricePrefix', label: 'Price prefix', widget: 'string', required: false, hint: 'Small word above the price, e.g. "från".' },
          { name: 'price', label: 'Price', widget: 'string', hint: 'e.g. "595 kr", "19 900 kr", "0 kr".' },
          { name: 'period', label: 'Period', widget: 'string', required: false, hint: 'e.g. "/mån" or "engångspris". Blank for none.' },
          { name: 'description', label: 'Description', widget: 'text', required: false },
          { name: 'features', label: 'Features', widget: 'list', required: false, fields: [{ name: 'text', label: 'Feature', widget: 'string' }] },
          { name: 'badge', label: 'Badge', widget: 'string', required: false, hint: 'Small label, e.g. "populär".' },
          { name: 'highlight', label: 'Highlight this plan', widget: 'boolean', required: false, default: false },
          { name: 'ctaLabel', label: 'Button label', widget: 'string', required: false },
          linkField('ctaHref', 'Button link'),
        ],
      },
      surfaceField,
    ],
  },
  { type: 'specialistGrid', label: 'Specialist grid', group: 'Cards & lists', summary: 'Grid of specialist / team profile cards.', shape: 'grid', fields: [...headingFields, cardListField, surfaceField] },
  {
    type: 'steps', label: 'Process / steps', group: 'Cards & lists', summary: 'Numbered process — a sequence of steps.', shape: 'steps',
    fields: [
      ...headingFields,
      {
        name: 'items', label: 'Steps', widget: 'list', required: false,
        fields: [
          { name: 'title', label: 'Title', widget: 'string' },
          { name: 'kicker', label: 'Tag after the number', widget: 'string', required: false, hint: 'Short word shown with the number, e.g. "talk".' },
          { name: 'body', label: 'Text', widget: 'text' },
        ],
      },
      widthField,
      surfaceField,
    ],
  },
  {
    type: 'checklist',
    label: 'Checklist',
    group: 'Cards & lists',
    summary: 'Ticked checklist items in one or two columns.',
    shape: 'checklist',
    fields: [
      ...headingFields,
      { name: 'items', label: 'Items', widget: 'list', required: false, fields: [{ name: 'text', label: 'Text', widget: 'string' }, { name: 'note', label: 'Sub-line (optional)', widget: 'text', required: false }] },
      { name: 'columns', label: 'Columns', widget: 'number', required: false, default: 2, hint: '1 or 2.' },
      surfaceField,
    ],
  },
  {
    type: 'gallery',
    label: 'Gallery',
    group: 'Media',
    summary: 'Image grid (2–3 columns) with optional captions.',
    shape: 'gallery',
    fields: [
      ...headingFields,
      { name: 'images', label: 'Images', widget: 'list', required: false, fields: [imageField('image', 'Image'), { name: 'alt', label: 'Alt text', widget: 'string', required: false }, { name: 'caption', label: 'Caption', widget: 'string', required: false }] },
      { name: 'columns', label: 'Columns', widget: 'number', required: false, default: 3, hint: '2 or 3.' },
      surfaceField,
    ],
  },
  {
    type: 'beforeAfter',
    label: 'Before / after',
    group: 'Media',
    summary: 'A before / after image pair.',
    shape: 'split',
    fields: [...headingFields, imageField('before', 'Before image'), imageField('after', 'After image'), surfaceField],
  },
  {
    type: 'textImage',
    label: 'Text + image',
    group: 'Text',
    summary: 'Text beside an image (image on the left or right).',
    shape: 'split',
    fields: [
      { name: 'heading', label: 'Heading', widget: 'string', required: false },
      { name: 'body', label: 'Text', widget: 'markdown' },
      imageField('image', 'Image'),
      { name: 'imageAlt', label: 'Alt text', widget: 'string', required: false },
      { name: 'flip', label: 'Image on left', widget: 'boolean', required: false, default: false },
      surfaceField,
    ],
  },
  {
    type: 'textQuote',
    label: 'Text + quote',
    group: 'Text',
    summary: 'Body text paired with a pulled-out quote.',
    shape: 'split',
    fields: [
      { name: 'body', label: 'Body text', widget: 'markdown' },
      { name: 'quote', label: 'Quote', widget: 'text' },
      { name: 'attribution', label: 'Source / name', widget: 'string', required: false },
      accentField,
      { name: 'flip', label: 'Quote on left', widget: 'boolean', required: false, default: false },
      surfaceField,
    ],
  },
  {
    type: 'definition',
    label: 'Dictionary entry',
    group: 'Quote & highlight',
    summary: 'A dictionary-style word entry — term, word class and numbered senses.',
    shape: 'prose',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', widget: 'string', required: false },
      { name: 'term', label: 'Term', widget: 'string', hint: 'The word being defined, e.g. "grö·na·re" (use · for syllables).' },
      { name: 'wordClass', label: 'Word class / etymology line', widget: 'string', required: false, hint: 'The italic line under the term, e.g. "komparativ av grön".' },
      {
        name: 'senses', label: 'Senses', widget: 'list', required: false,
        fields: [
          { name: 'text', label: 'Sense', widget: 'string', hint: 'Wrap words in *asterisks* to underline them.' },
          { name: 'note', label: 'Note (muted)', widget: 'string', required: false, hint: 'A quiet addendum after the sense, e.g. an example or year.' },
        ],
      },
      {
        name: 'width', label: 'Width', widget: 'select', required: false, default: 'xnarrow',
        options: [{ label: 'Extra narrow', value: 'xnarrow' }, { label: 'Narrow (reading column)', value: 'narrow' }, { label: 'Full width', value: 'full' }],
      },
      {
        name: 'align', label: 'Alignment', widget: 'select', required: false, default: 'left',
        options: [{ label: 'Left', value: 'left' }, { label: 'Centered', value: 'center' }, { label: 'Right', value: 'right' }],
      },
      surfaceField,
    ],
  },
  {
    type: 'fragment',
    label: 'Story fragment',
    group: 'Text',
    summary: 'A placed editorial fragment — big lead line, short body, optional link. Consecutive fragments drift across the page.',
    shape: 'prose',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', widget: 'string', required: false, hint: 'Usually only on the first fragment of a story.' },
      { name: 'statement', label: 'Statement (big line)', widget: 'string', hint: 'Wrap words in *asterisks* to underline them.' },
      { name: 'body', label: 'Text', widget: 'text', required: false },
      { name: 'linkLabel', label: 'Link label', widget: 'string', required: false },
      linkField('link', 'Link'),
      {
        name: 'placement', label: 'Placement', widget: 'select', required: false, default: 'left',
        hint: 'Where the fragment sits — alternate placements to break the grid.',
        options: [{ label: 'Left', value: 'left' }, { label: 'Right', value: 'right' }, { label: 'Indented', value: 'indent' }],
      },
      surfaceField,
    ],
  },
  {
    type: 'callout',
    label: 'Highlighted quote',
    group: 'Quote & highlight',
    summary: 'A single highlighted quote or statement.',
    shape: 'quote',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', widget: 'string', required: false },
      { name: 'quote', label: 'Quote / statement', widget: 'text', hint: 'Wrap words in *asterisks* to underline them.' },
      {
        name: 'width', label: 'Width', widget: 'select', required: false, default: 'narrow',
        hint: 'How wide the quote column is. Narrow reads best.',
        options: [
          { label: 'Narrow (reading column)', value: 'narrow' },
          { label: 'Extra narrow', value: 'xnarrow' },
          { label: 'Full width', value: 'full' },
        ],
      },
      {
        name: 'align', label: 'Alignment', widget: 'select', required: false, default: 'left',
        hint: 'Where the quote column sits in the section (the text stays left-aligned).',
        options: [
          { label: 'Left', value: 'left' },
          { label: 'Centered', value: 'center' },
          { label: 'Right', value: 'right' },
        ],
      },
      accentField,
      surfaceField,
    ],
  },
  {
    type: 'statPanel',
    label: 'Statement panel',
    group: 'Quote & highlight',
    summary: 'Dark panel with a big number, statement and badges.',
    shape: 'panel',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', widget: 'string', required: false },
      { name: 'heading', label: 'Heading', widget: 'string', required: false, hint: 'Wrap words in *asterisks* to underline them.' },
      { name: 'body', label: 'Body', widget: 'text', required: false },
      { name: 'badges', label: 'Badges', widget: 'list', required: false, field: { name: 'badge', label: 'Badge', widget: 'string' } },
      { name: 'statValue', label: 'Big number', widget: 'string', required: false },
      { name: 'statLabel', label: 'Number label', widget: 'string', required: false },
      {
        name: 'stats',
        label: 'Stat columns',
        widget: 'list',
        required: false,
        hint: 'Two or three side-by-side figures (e.g. a comparison). Replaces the single big number when filled.',
        fields: [
          { name: 'label', label: 'Label', widget: 'string', required: false },
          { name: 'value', label: 'Value', widget: 'string' },
          { name: 'note', label: 'Note', widget: 'text', required: false },
        ],
      },
      accentField,
    ],
  },
  {
    type: 'testimonials',
    label: 'Testimonials',
    group: 'From collections',
    summary: 'Customer testimonials from your Testimonials collection.',
    shape: 'quote',
    collection: 'testimonials',
    fields: [...headingFieldsWith('Happy customers', 'References'), surfaceField],
  },
  {
    type: 'linkChips',
    label: 'Link chips',
    group: 'From collections',
    summary: 'Chip links from your Areas collection (e.g. towns you serve).',
    shape: 'chips',
    collection: 'towns',
    fields: [...headingFieldsWith('Service areas', 'Where we work'), surfaceField],
  },
  {
    type: 'postList',
    label: 'Posts (blog / news)',
    group: 'From collections',
    summary: 'List of the latest posts — featured lead + a card grid with cover images. Works with the blog or any article listing.',
    shape: 'list',
    fields: [
      ...headingFields,
      { name: 'source', label: 'source', widget: 'hidden' },
      { name: 'base', label: 'base', widget: 'hidden' },
      { name: 'featured', label: 'Featured first post', widget: 'boolean', required: false, default: true, hint: 'Show the newest post as a large lead card.' },
      { name: 'showImages', label: 'Image previews', widget: 'boolean', required: false, default: true },
      { name: 'columns', label: 'Columns', widget: 'number', required: false, default: 3, hint: '2 or 3.' },
      surfaceField,
    ],
  },
  {
    type: 'catalogList',
    label: 'Catalog (for sale)',
    group: 'From collections',
    summary: 'For-sale items from a catalog listing — filterable cards with cover, status badge, price and specs.',
    shape: 'grid',
    fields: [
      ...headingFields,
      { name: 'source', label: 'source', widget: 'hidden' },
      { name: 'base', label: 'base', widget: 'hidden' },
      { name: 'filters', label: 'Category filters', widget: 'boolean', required: false, default: true },
      { name: 'showImages', label: 'Image previews', widget: 'boolean', required: false, default: true },
      { name: 'columns', label: 'Columns', widget: 'number', required: false, default: 3, hint: '2 or 3.' },
      surfaceField,
    ],
  },
  {
    type: 'ctaPanel',
    label: 'Call to action (band)',
    group: 'Calls to action',
    summary: 'Full-width call-to-action band with a button.',
    shape: 'band',
    fields: [...headingFields, { name: 'label', label: 'Button label', widget: 'string', required: false }, linkField('href', 'Button link')],
  },
  {
    type: 'ctaBox',
    label: 'Call to action (box)',
    group: 'Calls to action',
    summary: 'A boxed call-to-action: heading, text and a button.',
    shape: 'box',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', widget: 'string', required: false },
      { name: 'heading', label: 'Heading', widget: 'string' },
      { name: 'label', label: 'Button label', widget: 'string' },
      linkField('href', 'Button link'),
      { name: 'label2', label: 'Second button label', widget: 'string', required: false, hint: 'Shown as a quiet text link beside the button.' },
      linkField('href2', 'Second button link'),
      surfaceField,
    ],
  },
  {
    type: 'faq',
    label: 'FAQ',
    group: 'From collections',
    summary: 'FAQ from your FAQ collection — list, accordion, cards or split layout.',
    shape: 'list',
    collection: 'faq',
    fields: [
      { name: 'variant', label: 'Layout', widget: 'select', required: false, default: 'list', options: [{ label: 'List', value: 'list' }, { label: 'Accordion', value: 'accordion' }, { label: 'Cards', value: 'cards' }, { label: 'Split (index + reader)', value: 'split' }] },
      ...headingFields,
      { name: 'entries', label: 'Questions shown', widget: 'select', options: '$faq', multiple: true, required: false, hint: 'Pick specific questions (in order). Leave empty to use the tag filter or show all.' },
      { name: 'tag', label: 'Tag filter', widget: 'select', options: '$faqTags', required: false, hint: 'Show every question carrying this tag (tags are set on the questions). Ignored when questions are picked above.' },
      { name: 'asideHeading', label: 'Aside · heading', widget: 'string', required: false, default: 'Still have questions?' },
      { name: 'asideBody', label: 'Aside · text', widget: 'text', required: false, default: "Get in touch and we'll help you out." },
      { name: 'asideCtaLabel', label: 'Aside · button label', widget: 'string', required: false, default: 'Contact' },
      linkField('asideHref', 'Aside · button link'),
      surfaceField,
    ],
  },
  {
    type: 'statsBar',
    label: 'Stats / facts',
    group: 'Numbers',
    summary: 'A row of stats / facts (label + value).',
    shape: 'stats',
    fields: [
      { name: 'items', label: 'Facts (label + value)', widget: 'list', required: false, fields: [{ name: 'label', label: 'Label', widget: 'string' }, { name: 'value', label: 'Value', widget: 'string' }] },
    ],
  },
  {
    type: 'logoStrip', label: 'Logo strip', group: 'Numbers', shape: 'chips',
    summary: 'A centered row of partner / client names with an optional lead-in.',
    fields: [
      { name: 'lead', label: 'Lead-in', widget: 'string', required: false, hint: 'e.g. “Trusted by” or “Built on”.' },
      { name: 'logos', label: 'Names', widget: 'list', required: false, field: { name: 'name', label: 'Name', widget: 'string' } },
    ],
  },
  {
    type: 'contactForm', label: 'Contact form', group: 'Calls to action',
    summary: 'A contact form with an optional direct-contact card. Heading, intro, field labels and layout are all editable.', shape: 'band',
    fields: [
      { name: 'eyebrow', label: 'Eyebrow', widget: 'string', required: false, hint: 'Small uppercase label above the heading.' },
      { name: 'heading', label: 'Heading', widget: 'string', required: false, hint: 'Blank uses the page title.' },
      { name: 'intro', label: 'Intro / description', widget: 'text', required: false, hint: 'Optional line under the heading. Blank = hidden.' },
      // Field labels: required (so they never read as "optional"), editable, with defaults.
      // Empty falls back to the localized default at render. Phone is a show/hide toggle.
      { name: 'labelName', label: 'Field label — name', widget: 'string', default: 'Name' },
      { name: 'labelEmail', label: 'Field label — email', widget: 'string', default: 'Email' },
      { name: 'showPhone', label: 'Show the phone field', widget: 'boolean', required: false, default: true },
      { name: 'labelMessage', label: 'Field label — message', widget: 'string', default: 'Describe your project', hint: 'e.g. "What can we help you with?" — word it for your business.' },
      { name: 'submitLabel', label: 'Submit button text', widget: 'string', default: 'Send request', hint: 'The form\'s submit button.' },
      { name: 'showDirectContact', label: 'Show the direct-contact card', widget: 'boolean', required: false, default: true, hint: 'Off → the form fills the width (no phone/email card).' },
    ],
  },
  {
    type: 'contactCard', label: 'Contact card', group: 'Calls to action', shape: 'box',
    summary: 'A contact card placed anywhere, auto-filled from Contact settings. Tick what it shows.',
    fields: [
      { name: 'show', label: 'Show', widget: 'select', multiple: true, required: false,
        default: ['phone', 'email'],
        hint: 'Tick the parts to display. Anything with no info in Contact settings is skipped (e.g. the map needs an address with lat/lng).',
        options: [
          { label: 'Phone', value: 'phone' },
          { label: 'Email', value: 'email' },
          { label: 'Opening hours', value: 'hours' },
          { label: 'Address', value: 'address' },
          { label: 'Mini-map', value: 'map' },
          { label: 'Social links', value: 'socials' },
        ] },
      { name: 'label', label: 'Card heading', widget: 'string', required: false, default: 'Direct contact' },
      { name: 'tint', label: 'Tinted background', widget: 'boolean', required: false, default: true },
    ],
  },
  {
    type: 'findUs', label: 'Find us (map)', group: 'Calls to action', shape: 'split',
    summary: 'A map beside the address, contact and hours — auto-filled from Contact settings. Needs lat/lng on the address.',
    fields: [
      { name: 'heading', label: 'Heading', widget: 'string', required: false, default: 'Find us' },
      { name: 'showHours', label: 'Show opening hours', widget: 'boolean', required: false, default: true },
    ],
  },
];
